FORMAT: 1A
HOST: http://helloworld.bearden.io/

# HelloWorld

HelloWorld is my playing around with Apiary. This is the API Blueprint language learning
session for me.

## Language Collection [/languages]

### List All Languages [GET]

+ Response 200 (application/json)

        {
            "choices": [
                {
                    "language": "English",
                    "greeting": "Hello"
                }, {
                    "language": "French",
                    "greeting": "Hello"
                }, {
                    "language": "Spanish",
                    "greeting": "Hola"
                }
            ]
        }