FORMAT: 1A
HOST: http://helloworld.bearden.io/

# HelloWorld

HelloWorld is my playing around with Apiary. This is the API Blueprint language learning
session for me.

## Language Collection [/languages]

### List All Languages [GET]
Returns a list of all languages supported.

+ Response 200 (application/json)

        {
            "languages": [
                "language": "English",
                "language": "French",
                "language": "Spanish"
            ]
        }