FORMAT: 1A
HOST: http://helloworld.bearden.io/

# HelloWorld

HelloWorld is my playing around with Apiary. This is the API Blueprint language learning
session for me.

## Question [/questions/{question_id}]

+ Parameters
    + question_id (required, number, `1`) ... ID of the Question in form of an integer

+ Attributes
    + question: `Favourite programming language?` (string, required)
    + published_at: `2014-11-11T08:40:51.620Z` (string) - An ISO8601 date when the question was published
    + choices (array[Choice], required) - An array of Choice objects
    + url: /questions/1 (string)
    
## Choice [/questions/{question_id}/choices/{choice_id}]

+ Parameters
    + question_id (required, number, `1`) ... ID of the Question in form of an integer
    + choice_id (required, number, `1`) ... ID of the Choice in form of an integer

+ Attributes
    + choice: Swift (string, required)
    + votes: 0 (number, required)